#!/bin/bash

FIL=$@

F77=ifort
#OPT='-O2 -openmp -integer-size 64 -fp-model strict -no-ftz -traceback -check all -ipo -c'  # Debug
OPT='-O2 -openmp -integer-size 64 -fp-model strict -no-ftz -ipo -c'  # UIUC
#OPT='-O2 -openmp -integer-size 64 -fp-model strict -no-ftz -xHOST -ipo -c'  # LionXF

set echo

echo Compiling $FIL with $F77 with options $OPT ...

$F77 $OPT $FIL

echo Done.

unset echo

